<a href="https://colab.research.google.com/github/harshithsai218/GENAI/blob/main/ths_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆)
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'2.0.2'

In [ ]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


#### 3. Create a null vector of size 10 (★☆☆)
(**hint**: np.zeros)

In [ ]:
n=np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)
(**hint**: size, itemsize)

In [ ]:
print(n.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
(**hint**: array\[4\])

In [ ]:
n[4]=1
print(n[4])

1.0


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
(**hint**: np.arange)

In [ ]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)
(**hint**: array\[::-1\])

In [ ]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
(**hint**: reshape)

In [ ]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
(**hint**: np.nonzero)

In [ ]:
x=[1,2,0,0,4,0]
i=np.nonzero(x)
print(np.nonzero(x))
print(i[0])

(array([0, 1, 4]),)
[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)
(**hint**: np.eye)

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
(**hint**: np.random.random)

In [ ]:
print(np.random.random((3,3,3)))

[[[0.5398218  0.58192684 0.7570166 ]
  [0.27784939 0.42493523 0.86114353]
  [0.56467067 0.08358384 0.63434561]]

 [[0.04155439 0.90869188 0.35408889]
  [0.20309229 0.41995594 0.93946837]
  [0.73225244 0.2283804  0.76651929]]

 [[0.1272636  0.26786469 0.26513352]
  [0.95622254 0.65633302 0.16833621]
  [0.42363988 0.73464725 0.41248154]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
(**hint**: min, max)

In [ ]:
m=np.random.random((10,10))
print(m)
print(m.min())
print(m.max())

[[0.84930446 0.14088057 0.99782462 0.08061487 0.38994369 0.33076825
  0.64963257 0.37518939 0.60304016 0.2461003 ]
 [0.04707552 0.52426391 0.83935206 0.81446535 0.75907662 0.77902422
  0.06248518 0.25464095 0.3119069  0.17540472]
 [0.25861225 0.29091544 0.57426642 0.9652385  0.89152987 0.11945562
  0.62439997 0.82998436 0.82113519 0.448199  ]
 [0.05127485 0.32729904 0.32693201 0.20275079 0.14567319 0.63497536
  0.4376917  0.60642896 0.85183695 0.40005339]
 [0.18417123 0.63026442 0.33201127 0.86515126 0.97102855 0.59910944
  0.49038695 0.88924507 0.1103383  0.99398701]
 [0.8657296  0.90663983 0.16946045 0.22285741 0.52446587 0.37464809
  0.29956383 0.92841071 0.70364693 0.0016882 ]
 [0.56301342 0.04884929 0.38805535 0.85724444 0.34221971 0.22922571
  0.19953687 0.76440274 0.1055325  0.8330552 ]
 [0.38926774 0.14195252 0.66556909 0.55931067 0.84376396 0.01150236
  0.41703524 0.3010059  0.03868408 0.35453551]
 [0.90255902 0.94037614 0.86739077 0.35952698 0.80916426 0.43096834
  0.99038205

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
(**hint**: mean)

In [ ]:
m=np.random.random((30))
print(m)
print(m.mean())

[0.13982438 0.06188096 0.65733159 0.40874152 0.4234758  0.11476258
 0.9282357  0.90134403 0.9140307  0.75873355 0.34041703 0.69097269
 0.91701925 0.91711908 0.73648774 0.41028788 0.75131452 0.3892036
 0.78301836 0.88609243 0.48197819 0.20502269 0.88775225 0.37399535
 0.15144835 0.8160177  0.76735226 0.74438929 0.26307629 0.30397173]
0.5708432504524031


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
n=np.ones((5,5))
n[1:-1,1:-1]=0
c=np.pad(n,,'constant',constant_values=(5))
print(c)
print(n)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
(**hint**: np.pad)

In [ ]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.pad(n,1,'minimum'))

[[1 1 2 3 1]
 [1 1 2 3 1]
 [4 4 5 6 4]
 [7 7 8 9 7]
 [1 1 2 3 1]]


#### 17. What is the result of the following expression? (★☆☆)
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
(**hint**: np.diag)

In [ ]:
x=np.diag([1,2,3,4],-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
(**hint**: array\[::2\])

In [ ]:
x=np.zeros((8,8))
x[::2,1::2]=1
x[1::2,::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
(**hint**: np.unravel_index)

In [ ]:
x= np.unravel_index(100,(6,7,8))
print(x)

NameError: name 'np' is not defined

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
(**hint**: np.tile)

In [ ]:
x=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)
(**hint**: (x - min) / (max - min))

In [ ]:
x=np.random.random((5,5))
q=(x-x.min())/(x.max()-x.min())
print(x)
print("---")
print(q)

[[0.84057143 0.1694363  0.94708663 0.83899636 0.44338408]
 [0.73398735 0.65487652 0.23573332 0.45092237 0.83566885]
 [0.82350646 0.42111788 0.86793415 0.57548602 0.09651815]
 [0.08203174 0.44565547 0.2660223  0.0049203  0.13338861]
 [0.29463708 0.41181907 0.01906227 0.41691372 0.15376541]]
---
[[0.8869465  0.1746146  1.         0.88527475 0.46537832]
 [0.7738199  0.68985294 0.24498118 0.47337934 0.88174298]
 [0.86883402 0.44174534 0.91598885 0.60558916 0.09722047]
 [0.08184483 0.46778913 0.27712941 0.         0.13635417]
 [0.30750068 0.43187573 0.01501006 0.43728311 0.15798178]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
(**hint**: np.dot | @)

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a@b)
print(np.dot(a,b))
print(a.dot(b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
(**hint**: >, <=)

In [ ]:
n=np.arange(10)
n[(n>3)&(n<8)]*=-1
print(n)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z=10
print(z**z)
print(2<<z>>2)
print(z<-z)
print(1j*z)
print(z/1/1)
print(z<z>z)

10000000000
512
False
10j
10.0
False


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
x= np.array(0) / np.array(0)
y= np.array(0) // np.array(0)
z= np.array([np.nan]).astype(int).astype(float)
print(x)
print(y)
print(z)

nan
0
[-9.22337204e+18]


<ipython-input-37-6825e7ff5de5>:1: RuntimeWarning: invalid value encountered in divide
  x= np.array(0) / np.array(0)
<ipython-input-37-6825e7ff5de5>:2: RuntimeWarning: divide by zero encountered in floor_divide
  y= np.array(0) // np.array(0)
<ipython-input-37-6825e7ff5de5>:3: RuntimeWarning: invalid value encountered in cast
  z= np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
z=0.3
print(np.ceil(z))

1.0


#### 30. How to find common values between two arrays? (★☆☆)
(**hint**: np.intersect1d)

In [ ]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
x = np.intersect1d(a,b)
print(x)

[2 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆)
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
print(np.datetime64())

NaT


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
from datetime import datetime
print(np.arange(dtype=datetime['D']))

TypeError: type 'datetime.datetime' is not subscriptable

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
(**hint**: np.arange)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(**hint**: np.linspace)

In [ ]:
x= random.random(10)
print(x)
a=np.linspace(0,1,5)
print(a)

[0.46761717 0.62449266 0.29718464 0.82688398 0.67849356 0.50961926
 0.91951067 0.41761774 0.17366211 0.62235754]
[0.   0.25 0.5  0.75 1.  ]


#### 40. Create a random vector of size 10 and sort it (★★☆)
(**hint**: sort)

In [ ]:
x= random.random(10)
print(x)
print(np.sort(x))

[0.58832721 0.70555607 0.36596439 0.34738987 0.32316943 0.66146591
 0.53332946 0.98796221 0.79722266 0.22151236]
[0.22151236 0.32316943 0.34738987 0.36596439 0.53332946 0.58832721
 0.66146591 0.70555607 0.79722266 0.98796221]
